<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <groupId>com.mbm</groupId>
    <artifactId>ruleset-xom</artifactId>
    <version>1.0.0</version>

    <packaging>pom</packaging>

    <modules>
        <module>XOM</module>
        <module>Ruleapp</module>
    </modules>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>com.ibm.rules.buildcommand</groupId>
                    <artifactId>rules-compiler-maven-plugin</artifactId>
                    <version>8.10.1.0</version>
                    <extensions>true</extensions>
                </plugin>
                <plugin>
                    <groupId>com.hubspot.maven.plugins</groupId>
                    <artifactId>prettier-maven-plugin</artifactId>
                    <version>0.22</version>
                    <configuration>
                        <printWidth>120</printWidth>
                        <ignoreConfigFile>true</ignoreConfigFile>
                        <ignoreEditorConfig>false</ignoreEditorConfig>
                        <inputGlobs>
                            <!-- 
                            Include all .java files in this repository
                            Note: Specific files and directories (e.g., autogenerated classes in com/fs)
                            are excluded via the `.prettierignore` file to avoid formatting generated code.
                        -->
                            <inputGlob>**/src/com/**/*.java</inputGlob>
                        </inputGlobs>
                    </configuration>
                    <executions>
                        <execution>
                            <phase>validate</phase>
                            <goals>
                                <goal>write</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

</project>
